library(shiny)
library(DT)

ui <- fluidPage(
  theme = "bootstrap.css",
  hr(),
  titlePanel(title=div("Colorectal Cancer Stratification App by S:CORT",h6("Developed by Sanjay Rathee & Maintained by Andrew")), windowTitle = ""),  
  hr(),
  sidebarLayout(
    sidebarPanel(
      wellPanel(
        h4("Upload Validation Cohort"),
        hr(),
        # div(style="display: inline-block;vertical-align:top; width: 47%;",textInput("searchword", " Search Drug Name", value = "", width = NULL, placeholder = NULL)),
        #div(style="display: inline-block;vertical-align:top; width: 47%;",checkboxInput("checkGSE87211",value = TRUE, label = "Select GSE87211")),
        #hr(),
        #h4("Or"),
        fileInput("file1", "Upload Expression CSV File", accept = c("text/csv", "text/comma-separated-values,text/plain", ".csv")),
        fileInput("file2", "Upload Metadata CSV File", accept = c("text/csv", "text/comma-separated-values,text/plain", ".csv")),
        hr(),
        div(style="display: inline-block;vertical-align:top; width: 94%;",selectInput('choice', 'Select cohort size', selected = "Select" ,choices = c("Select","Full Cohort", "Balanced Cohort"))),
        div(style="display: inline-block;vertical-align:top; width: 47%;",actionButton("buttonValidateGse87211", "Validate Cohort")),
        div(style="display: inline-block;vertical-align:top; width: 47%;",actionButton("buttonPredictGse87211", "Predict Cohort")),
      ),
      wellPanel(
        h5("Disclaimer: We don not store any data uploaded here."),
        hr(),
        h5("All rights reserved to S:CORT"),
      ),
      # wellPanel(
      #   h4("Find Drug 2 Info in FDA Approved List"),
      #   hr(),
      #   fileInput("file1", "Upload Expression CSV File", accept = c("text/csv", "text/comma-separated-values,text/plain", ".csv")),
      #   fileInput("file2", "Upload Metadata CSV File", accept = c("text/csv", "text/comma-separated-values,text/plain", ".csv")),
      #   div(style="display: inline-block;vertical-align:top; width: 94%;",selectInput('choice2', 'Select cohort size', selected = "Select" ,choices = c("Select","Full Cohort", "Balanced Cohort"))),
      #   div(style="display: inline-block;vertical-align:top; width: 94%;",actionButton("buttonValidate", "Validate Data")),
      #   # div(style="display: inline-block;vertical-align:top; width: 47%;",selectInput('drug2', 'Select Drug Name', selected = "Select" ,choices = c("Select",unique(sort.default(imp_drugs$search_word))))),
      #   # div(style="display: inline-block;vertical-align:top; width: 0%;",HTML("<br>")),
      #   # div(style="display: inline-block;vertical-align:top; width: 47%;",textInput("searchword2", " Search Drug Name", value = "", width = NULL, placeholder = NULL)),
      #   # div(style="display: inline-block;vertical-align:top; width: 47%;",checkboxInput("checkInexactMatch2",value = FALSE, label = "Allow Inexact Match")),
      #   # div(style="display: inline-block;vertical-align:top; width: 47%;",checkboxInput("checkIngredientMatch2",value = FALSE, label = "Allow Ingredient Match")),
      #   # div(style="display: inline-block;vertical-align:top; width: 94%;",checkboxInput("checkDataElementsMatch2",value = FALSE, label = "Allow Data Elements Match")),
      #   # div(style="display: inline-block;vertical-align:top; width: 94%;",actionButton("buttonRecord2", "Get All Records")),
      #   # hr(),
      #   # div(style="display: inline-block;vertical-align:top; width: 94%;",uiOutput("selectedRecord2")),
      #   #div(style="display: inline-block;vertical-align:top; width: 94%;",actionButton("buttonSelectRecord", "Show Selected Record")),
      # ),
        
    ),
  
    mainPanel(
      tabsetPanel(type = "tabs",
                  tabPanel("Instructions",
                           h3(""),
                           h4("Please prepare the validation data as instructed:"),
                           hr(),
                           h5("1. Expression data csv file should have samples as columns and genes (Entrez ID only) as rows."),
                           h5("2. Metadata csv file should have samples as row and attributes(response, t-stage, n-stage) as column."),
                           h5("3. Metadata csv file for predictions should have only two attributes (t-stage and n-stage) as column."),
                           h5("4. Both csv files should have row and col names."),
                           h5("5. Put all t-stage and n-stage values as 1 if no data available."),
                           hr(),
                           #DT::dataTableOutput('sample_exp', width = "99%", height = "20em") %>% withSpinner(color="#0dc5c1"),
                           hr(),
                  ),
                  tabPanel("Validation Plots",
                           h3(""),
                           h5("Plots to show prediction probabilities and roc curve for  uploaded cohort. Please confirm if sample names in columns of expression data are same as sample name in row names of metadata. Metadata should have three columns as response, t-stage, n-stage."),
                           hr(),
                           plotOutput("probPlot", height = "20em") %>% withSpinner(color="#0dc5c1"),
                           hr(),
                           plotOutput("rocPlot", height = "20em") %>% withSpinner(color="#0dc5c1"),
                  ),
                  tabPanel("Validation Tables",
                           # column(8, wellPanel(
                           h5("Plots to show prediction probabilities and roc curve for  uploaded cohort Please confirm if sample names in columns of expression data are same as sample name in row names of metadata. Metadata should have three columns as response, t-stage, n-stage."),
                           hr(),
                           DT::dataTableOutput('predictionprobs', width = "99%", height = "20em") %>% withSpinner(color="#0dc5c1"),
                           hr(),
                           DT::dataTableOutput('predictionaccuracy', width = "99%", height = "10em") %>% withSpinner(color="#0dc5c1"),
                  ),
                  tabPanel("Prediction Tables",
                           # column(8, wellPanel(
                           h5("Plots to show prediction probabilities and roc curve for uploaded cohort. Please confirm if sample names in columns of expression data are same as sample name in row names of metadata. Metadata should have two columns as  t-stage, n-stage."),
                           hr(),
                           DT::dataTableOutput('predictionprobs2', width = "99%", height = "20em") %>% withSpinner(color="#0dc5c1"),
                  )
#                   # tabPanel("Drug2 Records",
#                   #          h3(""),
#                   #          h5("Showing only selected entry for searched drug 2 in FDA Data (Choose a record ID from all IDs). See other tabs to find more about selected drug"),
#                   #          hr(),
#                   #          DT::dataTableOutput('selectedRecords2', width = "99%", height = "14em") %>% withSpinner(color="#0dc5c1"),
#                   #          hr(),
#                   #          h5("Showing all entries for searched drug 2 in FDA Data"),
#                   #          hr(),
#                   #          DT::dataTableOutput('records2', width = "99%", height = "28em") %>% withSpinner(color="#0dc5c1"),
#                   # ),
#                   # tabPanel("Drug2 Dosage",
#                   #          # column(8, wellPanel(
#                   #          "FDA approved Drug 2 Dose Information",
#                   #          hr(),
#                   #          plotOutput("dosePlot2", height = "20em") %>% withSpinner(color="#0dc5c1"),
#                   #          hr(),
#                   #          DT::dataTableOutput('doseDataTable2', width = "99%", height = "28em") %>% withSpinner(color="#0dc5c1"),
#                   #          #)),
#                   # ),
#                   tabPanel("Drug Warnings",
#                            "FDA approved Drug Warnings Information",
#                            hr(),
#                            visNetworkOutput("warningsVisPlot") %>% withSpinner(color="#0dc5c1"),
#                            hr(),
#                            DT::dataTableOutput('warningsDataTable', width = "99%", height = "21em") %>% withSpinner(color="#0dc5c1"),
#                   ),
#                   tabPanel("Drug Sideeffects",
#                            "FDA approved Drug Sideeffects Information",
#                            hr(),
#                            visNetworkOutput("sideeffectsVisPlot") %>% withSpinner(color="#0dc5c1"),
#                            hr(),
#                            DT::dataTableOutput('sideeffectsDataTable', width = "99%", height = "21em") %>% withSpinner(color="#0dc5c1"),
#                   ),
#                   tabPanel("Drug Indications",
#                            "FDA approved Drug Indications Information",
#                            hr(),
#                            visNetworkOutput("indicationsVisPlot") %>% withSpinner(color="#0dc5c1"),
#                            hr(),
#                            DT::dataTableOutput('indicationsDataTable', width = "99%", height = "21em") %>% withSpinner(color="#0dc5c1"),
#                   )
# #                   tabPanel("Adverse Events",
# #                            "Drug Dose Code: 1X--Once or one time, BID--Twice a day, BIW--Twice a week, HS--At bedtime, PRN--As needed, Q12H--Every 12 hours, Q2H--Every 2 hours, Q3H--Every 3 hours,
# # 			                      Q3W--Every 3 weeks, Q4H--Every 4 hours, Q5H--Every 5 hours, Q6H--Every 6 hours, Q8H--Every 8 hours, QD--Daily, QH--Every hour, QID--4 times a day, QM--Monthly,
# # 			                      QOD--Every other day, QOW--Every other week, QW--Every week, TID--3 times a day, TIW--3 times a week, UNK--Unknown",
# #                            hr(),
# #                            plotOutput("plot8") %>% withSpinner(color="#0dc5c1"),
# #                            hr(),
# #                            DT::dataTableOutput('auid8', width = "99%", height = "21em") %>% withSpinner(color="#0dc5c1"),
# #                   ),
# #                   tabPanel("Events Indications",
# #                            "Drug Indication",
# #                            hr(),
# #                            plotOutput("plot7") %>% withSpinner(color="#0dc5c1"),
# #                            hr(),
# #                            DT::dataTableOutput('auid7', width = "99%", height = "21em") %>% withSpinner(color="#0dc5c1"),
# #                   ),
# #                   tabPanel("Events Outcomes",
# #                            "Drug Outcome : ",
# #                            h6("DE: Death, LT: Life-Threatening, HO: Hospitalization - Initial or Prolonged, DS: Disability, CA: Congenital Anomaly, RI: Required Intervention to Prevent Permanent Impairment/Damage, OT: Other Serious (Important Medical Event)"),
# #                            hr(),
# #                            plotOutput("plot6") %>% withSpinner(color="#0dc5c1"),
# #                            hr(),
# #                            DT::dataTableOutput('auid6', width = "99%", height = "21em") %>% withSpinner(color="#0dc5c1"),
# #                   ),
# #                   tabPanel("Download",
# #                            "Get List",
# #                            hr(),
# #                            DT::dataTableOutput('auid5', width = "99%", height = "21em") %>% withSpinner(color="#0dc5c1"),
# #                   )
      )
      
    ),
    
  )
  
  
  
)